language: android
sudo: false
android:
  components:
    - tools
    - build-tools-28.0.3
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    # The BuildTools version used by your project

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25
    - android-27
    - android-28

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-27
    - sys-img-armeabi-v7a-android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
script:
  - ./gradlew  assembleTravisRelease
jdk: oraclejdk8
os:
  - linux